services:

  mysql-8-0-36:
    image: mysql:8.0.36
    container_name: mysql-8-0-36
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
        - 3306:3306

  adminer:
    image: adminer:4.8.0-standalone
    container_name: adminer-4-8-0-standalone
    restart: always
    ports:
      - 9080:8080

